name: BarlowTwins_double_2x1024_20_256_time

model:
  name: barlow_twins
  backbone: resnet50
  castrate: True
  params:
    projector: '8192-8192'
    lambd: 0.0051

dataset:
  name: CATCH
  params:
    name: 10
    nearby: 0

aug:
  name: barlow_twins
  params:
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 300
  num_epochs: 400
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 13
num_workers: 4
tensorboard: True
pin_memory: True

matplotlib: True

resume:
  status: False
  ckpt: ../checkpoints/BarlowTwins_double_2x1024_20_256/ckpt_best_266.pth
  event: ../logs/in-progress_BarlowTwins_double_2x1024_20_256_0704032733/events.out.tfevents.1688441253.selab4
  