name: BarlowTwins_2x128_20_256

model:
  name: barlow_twins
  backbone: resnet50
  castrate: True
  params:
    projector: '128-128'
    lambd: 0.0051

dataset:
  name: CATCH
  params:
    name: 20

aug:
  name: barlow_twins
  params:
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 275
  num_epochs: 400
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 13
num_workers: 4
tensorboard: True
matplotlib: True

resume:
  status: True
  ckpt: ../checkpoints/BarlowTwins_2x128_20_256/ckpt_best_205.pth
  event: ../logs/in-progress_BarlowTwins_2x128_20_256_0530055100/events.out.tfevents.1685425861.selab4