name: BYOL_20_256

model:
  name: byol
  backbone: resnet50
  params:
    in_dim: 2048
    hidden_dim: 4096
    out_dim: 128
    m: 0.996

dataset:
  name: CATCH
  params:
    name: 20

aug:
  name: byol
  params:
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 274
  num_epochs: 400
  save_interval: 1
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: neg-cosine
    params:
      version: simplified
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 13
num_workers: 4
tensorboard: True
matplotlib: True
pin_memory: True
resume:
  status: True
  ckpt: ../checkpoints/BYOL_10_256/ckpt_197.pth
  event: ../logs/in-progress_BYOL_10_256_0728140416/events.out.tfevents.1690553057.selab2