name: MICLe_SimCLRAug_10_256

model:
  name: micle
  backbone: resnet50
  params:
    name: 10
    nearby: [0]


aug:
  name: single_simclr
  params:
    image_size: 128
    mean_std: [[0.4561, 0.2746, 0.1623], [0.2609, 0.1639, 0.0991]]


train:
  batch_size: 256
  criterion:
    name: supcon
    params:
      temperature: 0.1
  metrics: ['acc_1']


  optimizer:
      constant_predictor_lr: False

eval: None
seed: 17
num_workers: 2
tensorboard: True
matplotlib: True
pin_memory: True


resume:
  status: False
  ckpt: /content/drive/MyDrive/Notebook/checkpoints/MICLe_10_256/ckpt_best_012.pth
  event: /content/drive/MyDrive/Notebook/logs/in-progress_MICLe_10_256_0708175550/events.out.tfevents.1688838950.c7222913fca1