name: Tien_MoCo_10_256

model:
  name: moco
  backbone: resnet50
  params:
    dim: 128
    K: 65536
    m: 0.999
    T: 0.07
    mlp: False

dataset:
  name: CATCH
  params:
    name: 10

aug:
  name: moco
  params:
    image_size: 128
    version: v2

train:
  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 200
  num_epochs: 200
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: CE
    params: None
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001

  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.0001

eval:
  batch_size: 256
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/Tien_MoCo_10_256/ckpt_099.pth

  optimizer:
    name: sgd
    params:
      lr: 30
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 5
      warmup_lr: 0.1
      final_lr: 0.0001

seed: 47
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: True
  ckpt: ../checkpoints/Tien_MoCo_10_256/ckpt_best_096.pth
  event: ../logs/in-progress_Tien_MoCo_10_256_0414192325/events.out.tfevents.1681500205.selab3