name: OSupCon_8_32_30_nopre

model:
  name: supcon
  backbone: resnet50
  params:
    head: mlp
    feat_dim: 128

dataset:
  name: CATCH
  params:
    name: full
    nearby: [0, 2, 3,5,6, 7,4,8]

aug:
  name: supcon
  params:
    image_size: 128

train:
  batch_size: 32
  iters_to_accumulate: 1
  stop_epoch: 300
  num_epochs: 400
  save_interval: 2
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: nnsupcon
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval:
  resume: False
  batch_size: 512
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/OSupCon02_10_256/ckpt_best_149.pth
  name: e30_p100
  dataset: 100

  optimizer:
    name: sgd
    params:
      lr: 0.2
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.003

seed: 11
num_workers: 4
pin_memory: True
tensorboard: True
matplotlib: True


resume:
  status: True
  ckpt: ../checkpoints/OSupCon_8_32_20_nopre/ckpt_best_229.pth
  event: ../logs/completed_OSupCon_8_32_20_nopre_0727052419/events.out.tfevents.1690435459.selab3