name: Tien_SimCLR_20_512

model:
  name: simclr
  backbone: resnet50
  castrate: True
  params:
    dim: 128

dataset:
  name: CATCH
  params:
    name: 20

aug:
  name: simclr
  params:
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 2
  stop_epoch: 200
  num_epochs: 250
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.3
      momentum: 0.9
      weight_decay: 0.000001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval:
  batch_size: 256
  num_epochs: 50
  fold: 5
  eval_from: ../checkpoints/Tien_SimCLR_20_512/ckpt_099.pth

  optimizer:
    name: sgd
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001

seed: 12
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: True
  ckpt: ../checkpoints/Tien_SimCLR_20_512/ckpt_079.pth
  event: ../logs/in-progress_Tien_SimCLR_20_512_0424163358/events.out.tfevents.1682354038.selab3