name: SimCLR_20_256

model:
  name: simclr
  backbone: resnet50
  castrate: True
  params:
    dim: 128

dataset:
  name: CATCH
  params:
    name: 20

aug:
  name: simclr
  params:
    image_size: 128

train: None

eval:
  batch_size: 512
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/SimCLR_20_256/ckpt_274.pth
  name: e275_p100
  dataset: 100

  optimizer:
    name: sgd
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.001

seed: 19
num_workers: 4
tensorboard: True
matplotlib: True


resume:
  status: False
  ckpt: ../checkpoints/Tien_2B-2Neg_SupCon0_20_256/ckpt_best_250.pth
  event: ../logs/in-progress_Tien_2B-2Neg_SupCon0_20_256_0514131244/events.out.tfevents.1684069964.selab3