name: SimCLR_CATCH_100

model:
  name: simclr
  backbone: resnet50
  castrate: True
  params:
    dim: 128

dataset:
  name: CATCH
  params:
    name: 3

aug:
  name: simclr
  params:
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 8
  stop_epochs: 100
  num_epochs: 200
  save_interval: 5

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc@1']

  optimizer:
    name: sgd
    params:
      lr: 0.4
      momentum: 0.9
      weight_decay: 0.000001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.0001
      constant_predictor_lr: False

seed: 47
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: False
  ckpt: None
  event: None