name: SimCLR_10_512
model:
  name: simclr
  backbone: resnet50
  castrate: True
  params:
    dim: 128

dataset:
  name: CATCH
  params:
    name: 10

aug:
  name: simclr
  params:
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 2
  stop_epoch: 180
  num_epochs: 400
  save_interval: 1
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.000001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False
eval: None
seed: 47
num_workers: 4
tensorboard: True
matplotlib: True
pin_memory: True
resume:
  status: False
  ckpt: ../checkpoints/SimCLR_10_512/ckpt_best_012.pth
  event: ../logs/in-progress_SimCLR_10_512_0729024031/events.out.tfevents.1690598431.selab2