name: SimCLR_CATCH_100

model:
  name: simclr
  backbone: resnet18
  castrate: True
  params:
    dim: 128

dataset:
  name: CATCH
  params:
    center_list: ['../CATCH/TRAIN_SET']
    cancer: Melanoma
    patch_id: None

aug:
  name: simclr
  params:
    image_size: 224

train:
  batch_size: 128
  iters_to_accumulate: 8
  num_epochs: 15
  save_interval: 5

  criterion:
    name: NT-Xent
    params:
      temperature: 0.07
  metrics: ['acc@1', 'acc@5']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.000001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.0001
      final_lr: 0.00001

seed: None
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: False
  ckpt: None
  event: None