name: SimSiam_CIFAR10_100

model:
  name: simsiam
  backbone: resnet50
  params:
    dim: 2048
    pred_dim: 512

dataset:
  name: CATCH
  params:
    name: 3

aug:
  name: moco
  params:
    version: v2

train:
  batch_size: 128
  iters_to_accumulate: 4
  num_epochs: 100
  nodes: 1
  save_interval: 5

  criterion:
    name: neg-cosine
    params:
      version: simplified
  metrics: ['acc@1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.0001

seed: 47
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: False
  ckpt: None
  event: None