name: SimSiam_CIFAR10_100

model:
  name: simsiam
  backbone: resnet50
  params:
    proj_dim: 2048
    pred_dim: 512

dataset:
  name: CATCH
  params:
    name: 10

aug:
  name: moco
  params:
    image_size: 128
    version: v2

train:
  batch_size: 128
  iters_to_accumulate: 2
  stop_epoch: 200
  num_epochs: 200
  nodes: 1
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: neg-cosine
    params:
      version: simplified
  metrics: ['acc@1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 30
      warmup_lr: 0.01
      final_lr: 0.0005

seed: 47
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: False
  ckpt: None
  event: None