name: T_SimSiam_10_256

model:
  name: simsiam
  backbone: resnet50
  params:
    proj_dim: 2048
    pred_dim: 512

dataset:
  name: CATCH
  params:
    name: 10
    nearby: []

aug:
  name: moco
  params:
    version: v2
    image_size: 128

train:
  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 150
  num_epochs: 400
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: neg-cosine
    params:
      version: simplified
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 23
num_workers: 4
tensorboard: True
matplotlib: True
pin_memory: True
resume:
  status: False
  ckpt: ../checkpoints/T_SimSiam_10_256/ckpt_034.pth
  event: ../logs/in-progress_T_SimSiam_10_256_0614030417/events.out.tfevents.1686711857.selab2