name: Tien_SimTriplet_10_256

model:
  name: simtriplet
  backbone: resnet50
  params:
    proj_layers: 3

dataset:
  name: CATCH
  params:
    name: 10
    use_nearby: True
    patch_id: 0

aug:
  name: moco
  params:
    version: v2
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 2
  stop_epoch: 200
  num_epochs: 200
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: neg-cosine
    params: None
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 30
      warmup_lr: 0.01
      final_lr: 0.0005

eval:
  batch_size: 256
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/Tien_SimTriplet_10_256/ckpt_149.pth

  optimizer:
    name: sgd
    params:
      lr: 30
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 5
      warmup_lr: 0.1
      final_lr: 0.0001

seed: 47
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: True
  ckpt: ../checkpoints/Tien_SimTriplet_10_256/ckpt_104.pth
  event: ../logs/in-progress_Tien_SimTriplet_10_256_0418064000/events.out.tfevents.1681800000.selab3