name: SimTriplet_CATCH_100

model:
  name: simtriplet
  backbone: resnet50
  params:
    proj_layers: 3

dataset:
  name: CATCH
  params:
    center_list: ['/content/Histiocytoma/TRAIN_SET', '/content/Melanoma/TRAIN_SET']
    cancer: None
    patch_id: None

aug:
  name: moco
  params:
    version: v2
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 4
  num_epochs: 100
  save_interval: 5

  criterion:
    name: neg-cosine
    params: None
  metrics: ['acc@1', 'acc@5']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 30
      warmup_lr: 0.01
      final_lr: 0.00005


seed: None
num_workers: 1
tensorboard: True
matplotlib: True

resume:
  status: False
  ckpt: None
  event: None