name: SimTriplet_10_256

model:
  name: simtriplet
  backbone: resnet50
  params:
    proj_layers: 3

dataset:
  name: CATCH
  params:
    name: 10
    nearby: [0]

aug:
  name: moco
  params:
    version: v2
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 2
  stop_epoch: 150
  num_epochs: 400
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: neg-cosine
    params: None
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 17
num_workers: 4
tensorboard: True
matplotlib: True

resume:
  status: True
  ckpt: ../checkpoints/SimTriplet_10_256/ckpt_124.pth
  event: ../logs/in-progress_SimTriplet_10_256_0613213018/events.out.tfevents.1686691818.selab4