name: Tien_SupCon07_10_256

model:
  name: supcon
  backbone: resnet50
  params:
    head: mlp
    feat_dim: 128

dataset:
  name: CATCH
  params:
    name: 10
    nearby: [0, 7]

aug:
  name: supcon
  params:
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 2
  stop_epoch: 200
  num_epochs: 250
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: supcon
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval:
  batch_size: 256
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/Tien_SupCon07_10_256/ckpt_049.pth
  name: e50_p10
  dataset: 10

  optimizer:
    name: sgd
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001

seed: 7
num_workers: 4
tensorboard: True
matplotlib: True


resume:
  status: True
  ckpt: ../checkpoints/Tien_SupCon07_10_256/ckpt_best_015.pth
  event: ../logs/in-progress_Tien_SupCon07_10_256_0504095957/events.out.tfevents.1683194397.selab3