name: SupCon0DB_20_256

model:
  name: supcon
  backbone: resnet50
  params:
    head: mlp
    feat_dim: 128

dataset:
  name: DBCATCH
  params:
    name: 20
    nearby: 0

aug:
  name: supcon
  params:
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 2
  stop_epoch: 275
  num_epochs: 400
  save_interval: 2
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: supcon
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 19
num_workers: 4
tensorboard: True
matplotlib: True


resume:
  status: True
  ckpt: ../checkpoints/SupCon0DB_20_256/ckpt_249.pth
  event: ../logs/in-progress_SupCon0DB_20_256_0618132225/events.out.tfevents.1687094545.selab4