name: Tien_SupCon_10_256

model:
  name: supcon
  backbone: resnet50
  params:
    head: mlp
    feat_dim: 128

dataset:
  name: CATCH
  params:
    name: 20
    use_nearby: True
    patch_id: 0

aug:
  name: supcon
  params:
    image_size: 128

train:
  batch_size: 128
  iters_to_accumulate: 4
  stop_epoch: 200
  num_epochs: 250
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: supcon
    params:
      temperature: 0.07
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval:
  batch_size: 256
  num_epochs: 30
  fold: 5
  eval_from: ../checkpoints/Tien_SupCon_10_256/ckpt_best_099.pth
  name: e100_p75
  dataset: 75

  optimizer:
    name: sgd
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001

seed: 17
num_workers: 1
tensorboard: True
matplotlib: True


resume:
  status: True
  ckpt: ../checkpoints/MaskTien_SupCon_10_256/ckpt_best_099.pth
  event: None