name: SupervisedSGD_NewVAL_100_512

model:
  name: supervised
  backbone: resnet50
  params:
    num_classes: 6

dataset:
  name: finetune
  params:
    name: 100

aug:
  name: single_simclr
  params:
    image_size: 128

train:
  batch_size: 512
  iters_to_accumulate: 1
  stop_epoch: 100
  num_epochs: 100
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: focal
    params: None
  metrics: []

  optimizer:
    name: sgd
    params:
      lr: 0.005
      momentum: 0.9
      weight_decay: 0.00001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.001
      final_lr: 0.00001
      constant_predictor_lr: False

eval: None

seed: 19
num_workers: 4
tensorboard: True
matplotlib: True


resume:
  status: False
  ckpt: ../checkpoints/SupervisedSGD_NewVAL_100_256/ckpt_049.pth
  event: ../logs/completed_SupervisedSGD_NewVAL_100_256_0531025737/events.out.tfevents.1685501857.selab4