name: SwAV_10_256

model:
  name: swav
  backbone: resnet50
  params:
    hidden_dim: 2048
    proj_dim: 128
    nmb_prototypes: 3000
    normalize: True

dataset:
  name: SCCATCH
  params:
    name: 10
    nearby: [0]

aug:
  name: swav
  params:
    image_size: 128
    size_crops: [128]
    nmb_crops: [1]
    min_scale_crops: [0.08]
    max_scale_crops: [1]

train:
  crops_for_assign: [0]

  batch_size: 256
  iters_to_accumulate: 1
  stop_epoch: 150
  num_epochs: 400
  save_interval: 5
  knn_monitor: True
  knn_interval: 5
  knn_k: 200

  criterion:
    name: swav
    params:
      temperature: 0.1 
      epsilon: 0.5
      sinkhorn_iterations: 3
  metrics: ['acc_1']

  optimizer:
    name: sgd
    params:
      lr: 0.05
      momentum: 0.9
      weight_decay: 0.0001
      
  scheduler:
    name: lr_scheduler
    params:
      warmup_epochs: 10
      warmup_lr: 0.01
      final_lr: 0.0001
      constant_predictor_lr: False

eval: None

seed: 19
num_workers: 2
tensorboard: True
matplotlib: True
pin_memory: True


resume:
  status: False
  ckpt: ../checkpoints/SupCon0DB_20_256/ckpt_249.pth
  event: ../logs/in-progress_SupCon0DB_20_256_0618132225/events.out.tfevents.1687094545.selab4